name: ML-TerrainGeneration-Torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aom=3.8.2
  - av=11.0.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cccl=12.3.101
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.3.101
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.1.0
  - dav1d=1.2.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - graphite2=1.3.13
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - harfbuzz=8.3.0
  - icu=73.2
  - idna=3.4
  - importlib-metadata=7.1.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.4
  - libglib=2.80.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsqlite=3.45.2
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.4.1
  - openjpeg=2.4.0
  - openssl=3.2.1
  - pcre2=10.43
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.43.4
  - protobuf=3.20.3
  - python=3.12.2
  - python_abi=3.12
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - re2=2022.04.01
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - svt-av1=2.0.0
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tk=8.6.13
  - typing_extensions=4.9.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.1.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - werkzeug=3.0.1
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xz=5.4.5
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torchaudio==2.2.1
      - torchvision==0.17.1
